os: linux
dist: xenial
import:
- source: qasimabdullah404/travis-env-vars-test:.travis.yml
before_install:
  - set -e
  - free -m
  - source <(curl https://raw.githubusercontent.com/qasimabdullah404/travis-env-vars-test/main/test.sh)

script:
  - echo $testVar
  - echo $foo