os: linux
dist: xenial
before_install:
  - set -e
  - free -m
  - source <(curl https://raw.githubusercontent.com/qasimabdullah404/travis-env-vars-test/main/test.sh)
import:
  - source: qasimabdullah404/travis-env-vars-test:test.yml@main
script:
  - echo $testVar
  - echo $TEST_URL